from openjdk:16

WORKDIR /usr/app

COPY ms/mysql-connector-java-5.1.45-bin.jar lib/
ENV CLASSPATH=.:lib/mysql-connector-java-5.1.45-bin.jar:${CLASSPATH}


COPY ms/Configuration-tmplt.java ./
RUN sed "s/<PASSWORD>//g" < Configuration-tmplt.java > Configuration.java
RUN rm Configuration-tmplt.java
COPY ms/registry.properties ms/OrdersUI.java ms/MSClientAPI.java ms/CreateServicesAI.java ms/RetrieveServicesAI.java ms/DeleteServicesAI.java ms/AuthServiceAI.java ms/LoggerClient.java ms/LogServiceAI.java ./
RUN javac *.java

CMD java OrdersUI